### PR TITLE
:heart: A lovely Gandi design team gift :heart:

### PR DESCRIPTION
**Pull request by nlewo**
Today, the Gandi design team is proposing a go-gandi community lovely logo!

- [the logo proposal](https://github.com/go-gandi/terraform-provider-gandi/blob/logo/go-gandi.svg)
- [the rendered README](https://github.com/go-gandi/terraform-provider-gandi/blob/logo/README.md)

We could then use this logo on
- the [Github go-gandi organization page](https://github.com/go-gandi)
- the [Gandi Terraform registry page](https://registry.terraform.io/providers/go-gandi/gandi/2.0.0)

wdyt?

### CODE REVIEW

**Comment by tiramiseb** [comment]
I love it!

**Comment by scottmuc** [comment]
This is fantastic. Congrats on the recognition from gandi!

**Comment by robbyoconnor** [comment]
:shipit: Thank you Gandi!

**Comment by nlewo** [comment]
So, i updated the GitHub orga and Terraform avatar!

**Pull request merged**
