### PR TITLE
Run acceptance tests in Sandbox

### PR DESCRIPTION
**Pull request by nlewo**
So, this is PR would allow us to start adding tests! This is far from being perfect since it's not possible to easily run them locally :(

But i think it's still better than no tests at all.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Oh snap, @nlewo you work for Gandi? Noice!

**Comment by nlewo** [comment]
@robbyoconnor that's correct:)

So, this is PR would allow us to start adding tests! This is far from being perfect since it's not possible to easily run them locally :(

But i think it's still better than no tests at all.

**Comment by tiramiseb** [comment]
lgtm

**Comment by nlewo** [comment]
Ok, so, let's move forward then. 
If we find it annoying in next PRs, we could still revert this commit.

**Pull request merged**
