### PR TITLE
readme: this is not an officially supported Gandi project

### PR DESCRIPTION
**Pull request by nlewo**
Fixes https://github.com/go-gandi/terraform-provider-gandi/issues/113

### CODE REVIEW

**Comment by tiramiseb** [comment]
Maybe merge this information with what is already in the "Licensing" section...

**Comment by nlewo** [comment]
@tiramiseb Thanks for pointing this section! I didn't know it ;)

However, I think it's nice to put this message in the first lines of the readme: i'm not sure the user who opened the issue #113 had seen this message.

@tiramiseb I added a commit updating your status from main to initial. Would that be ok for you?

**Comment by tiramiseb** [comment]
Perfect.

Don't hesitate to move this section to the top if you think it's better

**Comment by nlewo** [comment]
@tiramiseb thx for the review!

**Pull request merged**
