### PR TITLE
Just updating deps for PR #56

### PR DESCRIPTION
**Pull request by robbyoconnor**
This is just updating the deps for #56

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@tiramiseb I'll look at the linting errors later today

**Comment by robbyoconnor** [comment]
@tiramiseb done.

**Comment by robbyoconnor** [comment]
I'm not seeing anymore linting errors locally...

**Comment by robbyoconnor** [comment]
image

**Comment by tiramiseb** [comment]
it's weird.
https://github.com/go-gandi/terraform-provider-gandi/pull/60/checks?check_run_id=3937690580
Unfortunately, I don't have time to check it in details these days...

**Pull request merged**
