### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by nlewo**
Last steps before a release!

Once this PR merged, I will have to
- push the tag `v2.0.0` to create a release
- publish this provider from the Terraform registry.

### CODE REVIEW

**Review by tiramiseb — APPROVED** [review]

**Comment by robbyoconnor** [comment]
Can we also publish this to the [Terraform Registry](https://registry.terraform.io)?

**Comment by tiramiseb** [comment]
> Can we also publish this to the [Terraform Registry](https://registry.terraform.io)?

@nlewo wrote he will publish it, in the first message of the conversation :wink: 

BTW, many many thanks @nlewo for the hard work!

**Comment by nlewo** [comment]
I'm planning to release beginning of next week.

(I think i updated the description, so it didn't appear in the mail notif)

**Comment by nlewo** [comment]
@tiramiseb I sent you 2 mails to the address from your GitHub profile (about a potential Gandi post). Did you receive it? (maybe i'm going to your spam :/)

**Comment by tiramiseb** [comment]
sorry, it's because a mix between work (over)load (for not answering right away) and ADHD (for forgetting to answer). I'm going to answer. Right Now. So that I don't forget. Sorry again :-)

**Comment by nlewo** [comment]
@tiramiseb No problem. I just wanted to be sure my mail was not going through your Gandi mail filtering rules ;)

**Comment by robbyoconnor** [comment]
@nlewo Can I just say how much I appreciate you doing this? :)

**Comment by debovema** [comment]
Seems online : https://registry.terraform.io/providers/go-gandi/gandi/latest

image

**Comment by nlewo** [comment]
I forgot to mention it, but Gandi published a news related to our release ;)

https://news.gandi.net/en/2022/01/first-published-release-of-the-community-terraform-gandi-provider-v2-0-0/

**Pull request merged**
